name: Update Play Store listing

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo pip3 install google-api-python-client oauth2client
      - name: Update listing
        run: python3 update-listing.py
        env:
          SERVICEACCOUNT: ${{ secrets.SERVICEACCOUNT }}
          SERVICEACCOUNT_EMAIL: ${{ secrets.SERVICEACCOUNT_EMAIL }}
